[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
